package com.InnovaServe.core.security;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Locale;

public enum Permission {
  TENANT_PROFILE_MANAGE,
  STAFF_READ,
  STAFF_MANAGE,
  ROLE_READ,
  ROLE_MANAGE,
  CUSTOMER_READ,
  CUSTOMER_WRITE,
  TAX_READ,
  TAX_MANAGE,
  ACCOUNT_READ,
  ACCOUNT_MANAGE,
  BILLING_READ,
  BILLING_CREATE,
  PAYMENT_RECORD,
  ROOM_READ,
  ROOM_MANAGE,
  HOUSEKEEPING_UPDATE,
  STAY_READ,
  STAY_CHECKIN,
  STAY_MANAGE,
  STAY_CHARGE,
  STAY_CHECKOUT,
  FORM_C_READ,
  FORM_C_SUBMIT,
  MENU_READ,
  MENU_MANAGE,
  TABLE_READ,
  TABLE_MANAGE,
  TABLE_CLEAR,
  QR_CODE_MANAGE,
  CREDIT_NOTE_CREATE,
  ORDER_READ,
  ORDER_CREATE,
  ORDER_CONFIRM,
  KITCHEN_READ,
  KITCHEN_MANAGE,
  SERVICE_PERFORMANCE_READ,
  BILL_CREATE,
  BILL_SETTLE,
  INVENTORY_READ,
  INVENTORY_MANAGE,
  EXPENSE_READ,
  EXPENSE_CREATE,
  EXPENSE_APPROVE,
  EXPENSE_REPORT,
  PETTY_CASH_MANAGE,
  RECURRING_EXPENSE_MANAGE,
  AUDIT_READ,
  TENANT_SUBSCRIPTION_READ,
  TENANT_SUBSCRIPTION_REQUEST,
  APPROVAL_PIN_VERIFY;

  @JsonCreator
  public static Permission fromJson(String value) {
    if (value == null) return null;
    return Permission.valueOf(
        value.trim().replace('-', '_').replace(' ', '_').toUpperCase(Locale.ROOT));
  }
}
