spring.application.name=InnovaServe
app.jwt.secret=${APP_JWT_SECRET}
spring.flyway.enabled=true
spring.flyway.schemas=core,stay,restaurant,expense
spring.flyway.default-schema=core

spring.datasource.url=jdbc:postgresql://ep-old-unit-b3j4uwq1.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_r2K0UPSzlWHO

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.hibernate.SQL=DEBUG
