spring.application.name=InnovaServe
spring.flyway.enabled=true
spring.flyway.schemas=core,stay,restaurant,expense
spring.flyway.default-schema=core

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.hibernate.SQL=DEBUG