package com.InnovaServe.api;
import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;import org.springframework.dao.DataIntegrityViolationException;import java.util.*;
@RestControllerAdvice public class ApiExceptionHandler{
 @ExceptionHandler(NoSuchElementException.class) public ResponseEntity<?> notFound(NoSuchElementException ex){String message=ex.getMessage()==null?"Resource not found":ex.getMessage();String code="RoomNotFound".equals(message)?"RoomNotFound":"NotFound";return ResponseEntity.status(404).body(Map.of("error",code,"message",message,"details",Map.of()));}
 @ExceptionHandler(IllegalArgumentException.class) public ResponseEntity<?> badRequest(IllegalArgumentException ex){String code="InvalidRequest";int status=400;if("InvalidCredentials".equals(ex.getMessage())){code="InvalidCredentials";status=401;}else if("PhoneAlreadyExists".equals(ex.getMessage())){code="PhoneAlreadyExists";status=409;}return ResponseEntity.status(status).body(Map.of("error",code,"message",ex.getMessage()==null?"Invalid request":ex.getMessage(),"details",Map.of()));}
 @ExceptionHandler(IllegalStateException.class) public ResponseEntity<?> conflict(IllegalStateException ex){String message=ex.getMessage()==null?"Request conflicts with current resource state":ex.getMessage();String code=switch(message){case "RoomNotAvailable"->"RoomNotAvailable";case "AccountClosed"->"AccountClosed";case "HasUnsettledCharges"->"HasUnsettledCharges";case "AlreadyLocked"->"AlreadyLocked";case "AlreadyApproved"->"AlreadyApproved";default->"InvalidState";};return ResponseEntity.status(409).body(Map.of("error",code,"message",message,"details",Map.of()));}
 @ExceptionHandler(SecurityException.class)public ResponseEntity<?> forbidden(SecurityException ex){return ResponseEntity.status(403).body(Map.of("error","Forbidden","message",ex.getMessage()==null?"Permission denied":ex.getMessage(),"details",Map.of()));}
 @ExceptionHandler(DataIntegrityViolationException.class)public ResponseEntity<?> constraint(DataIntegrityViolationException ex){return ResponseEntity.status(409).body(Map.of("error","Conflict","message","The request conflicts with an existing record or schema constraint","details",Map.of()));}
 @ExceptionHandler(Exception.class) public ResponseEntity<?> internal(Exception ex){return ResponseEntity.internalServerError().body(Map.of("error","InternalError","message","Request could not be completed","details",Map.of()));}
}
